// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 yoyicue

#ifndef IONSTACK_PROFILE_H
#define IONSTACK_PROFILE_H

#if (defined(IONSTACK_PROFILE_XPAD2_V260) +                                    \
     defined(IONSTACK_PROFILE_XPAD2_V19_A) +                                   \
     defined(IONSTACK_PROFILE_XPAD2_V19_B)) != 1
#error "select exactly one supported XPad2 profile"
#endif

#define EXPECTED_DEVICE "ls12_mt8797_wifi_64"
#define EXPECTED_KERNEL_RELEASE "4.19.191"
#define EXPECTED_SDK "33"
#define EXPECTED_FINGERPRINT_PREFIX                                           \
  "alps/vnd_ls12_mt8797_wifi_64/ls12_mt8797_wifi_64:13/"                     \
  "TP1A.220624.014/"
#define EXPECTED_FINGERPRINT_SUFFIX ":user/release-keys"
#define RELEASE_FINGERPRINT_INCREMENTAL_MIN 19U
#define RELEASE_FINGERPRINT_INCREMENTAL_MAX 260U
#if defined(IONSTACK_PROFILE_XPAD2_V260)

#define IONSTACK_PROFILE_NAME "xpad2-v260"
#define BUILD_VARIANT_LABEL "talih_pd2_mt8797_android13_4.19.191"
#define EXPECTED_KERNEL_VERSION "#1 SMP PREEMPT Mon Jun 29 04:08:29 CST 2026"
#define PROFILE_FINGERPRINT_INCREMENTAL_MIN RELEASE_FINGERPRINT_INCREMENTAL_MIN
#define PROFILE_FINGERPRINT_INCREMENTAL_MAX RELEASE_FINGERPRINT_INCREMENTAL_MAX

#elif defined(IONSTACK_PROFILE_XPAD2_V19_A)

#define IONSTACK_PROFILE_NAME "xpad2-v19-a"
#define BUILD_VARIANT_LABEL "talih_pd2_mt8797_android13_4.19.191_v19_boot_a"
#define EXPECTED_KERNEL_VERSION "#1 SMP PREEMPT Tue Aug 13 02:06:24 CST 2024"
#define PROFILE_FINGERPRINT_INCREMENTAL_MIN RELEASE_FINGERPRINT_INCREMENTAL_MIN
#define PROFILE_FINGERPRINT_INCREMENTAL_MAX RELEASE_FINGERPRINT_INCREMENTAL_MAX

#elif defined(IONSTACK_PROFILE_XPAD2_V19_B)

#define IONSTACK_PROFILE_NAME "xpad2-v19-b"
#define BUILD_VARIANT_LABEL "talih_pd2_mt8797_android13_4.19.191_v19_boot_b"
#define EXPECTED_KERNEL_VERSION "#1 SMP PREEMPT Mon Dec 16 23:29:13 CST 2024"
#define PROFILE_FINGERPRINT_INCREMENTAL_MIN RELEASE_FINGERPRINT_INCREMENTAL_MIN
#define PROFILE_FINGERPRINT_INCREMENTAL_MAX RELEASE_FINGERPRINT_INCREMENTAL_MAX

#endif

#endif
